include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    # treat warning as error
    # missing_required_param: error
    # missing_return: error
    # must_be_immutable: error
    # sort_constructors_first: ignore
    # prefer_const_constructors_in_immutables: ignore
    # prefer_const_constructors: ignore
    # prefer_const_literals_to_create_immutables: ignore
    # avoid_redundant_argument_values: ignore
    pass

linter:
  rules:
    # Add lint rules here later
    pass
