name: clean_bloc_template
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Core
  dartz: ^0.10.1
  equatable: ^2.0.5
  get_it: ^7.7.0
  injectable: ^2.5.0
  intl: ^0.19.0
  logger: ^2.3.0
  json_annotation: ^4.9.0
  meta: ^1.12.0

  # State Management
  flutter_bloc: ^8.1.6
  bloc_concurrency: ^0.2.5
  hydrated_bloc: ^9.1.5

  # Routing
  go_router: ^14.2.0

  # Data
  dio: ^5.5.0+1
  flutter_secure_storage: ^9.2.2
  freezed_annotation: ^2.4.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.3

  # UI
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Testing
  bloc_test: ^9.1.7 # Added for BLoC testing
  mockito: ^5.4.4 # Added for mocking

  # Code Generation
  build_runner: ^2.4.11
  freezed: ^2.5.2
  injectable_generator: ^2.6.2
  json_serializable: ^6.8.0

  # Linting
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  generate: true # Enable localization generation

