name: core_ui
description: Core UI components, theming, and utilities shared across features.
version: 0.1.0 # It's good practice to version local packages
publish_to: 'none' # Prevents accidental publishing to pub.dev

environment:
  sdk: '>=3.0.0 <4.0.0' # Adjust to your project's Flutter SDK constraint
  flutter: ">=1.17.0" # If using specific Flutter versions for UI components

dependencies:
  flutter:
    sdk: flutter
  # Add other common UI-related dependencies if needed by core_ui itself
  # e.g., flutter_svg: ^2.0.7
  # intl: ^0.18.1 # For formatting, if core_ui provides formatted text widgets

dev_dependencies:
  flutter_test:
    sdk: flutter
  # build_runner: ^2.4.0 # If you use code generation (e.g., for icons, theming)
  # flutter_lints: ^3.0.0 # Recommended lints
