name: feature_auth
description: Authentication feature module, including login, registration, etc.
version: 0.1.0
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0' # Adjust to your project's Flutter SDK constraint
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # Local package dependency on core_ui
  # Melos will handle linking this via pubspec_overrides.yaml in the root
  core_ui:
    path: ../core_ui

  # Add other dependencies specific to this feature
  # e.g., dartz: ^0.10.1 (for Either type in use cases/repositories)
  # get_it: ^7.6.0 (if using GetIt for DI within the feature)
  # flutter_bloc: ^8.1.3 (if using BLoC for state management)

dev_dependencies:
  flutter_test:
    sdk: flutter
  # mocktail: ^1.0.0 # For mocking dependencies in tests
  # build_runner: ^2.4.0 # If using code generation
  # flutter_lints: ^3.0.0 # Recommended lints
