import 'package:flutter/widgets.dart';

// THIS IS A MINIMAL PLACEHOLDER TO ALLOW COMPILATION.
// THE ACTUAL FILE SHOULD BE GENERATED BY `flutter gen-l10n`.

class AppLocalizations {
  AppLocalizations(this.locale);

  final Locale locale;

  static AppLocalizations? of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations);
  }

  static const LocalizationsDelegate<AppLocalizations> delegate = _AppLocalizationsDelegate();

  static const List<Locale> supportedLocales = [
    Locale('en', ''), // English, no country code
    // Add other supported locales here based on your arb files eventually
  ];

  // Add dummy getters for any strings that might be immediately needed
  // Example:
  // String get appTitle => 'My App';
}

class _AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    return AppLocalizations.supportedLocales.any((supportedLocale) => supportedLocale.languageCode == locale.languageCode);
  }

  @override
  Future<AppLocalizations> load(Locale locale) async {
    // In a real generated file, this would load the ARB data.
    // For this placeholder, we just return a basic instance.
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}
