name: ai_enhancer
description: A CLI tool to analyze and enhance the Flutter project structure.
version: 0.0.1
publish_to: 'none'

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  analyzer: ^6.4.1
  args: ^2.5.0
  path: ^1.9.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.2
